### ISSUE TITLE
Add: Docker-compose.yml and .env 

### ISSUE THREAD

**Issue by cbytestech** [SCORP1ON-TEAM/osint#32]
I wasn't sure of what "volumes" would be needed for this, but a barebones docker-compose.yml has been started for this. I'm pulling some of the defaults from the [previous docker project I was contributing to](https://github.com/sebgl/htpc-download-box)..

I realize a docker-compose might not be necessary for most, but I thought it would be a nice addition as I run a few containers on the same device, thinking I'm not alone.

[Install docker-compose](https://docs.docker.com/compose/install/)

  ```
version: "3.4"
services:
#  vpn:
#    container_name: vpn
#    image: dperson/openvpn-client:latest
#    cap_add:
#      - net_admin # required to modify network interfaces
#    restart: unless-stopped
#    volumes:
#      - /dev/net:/dev/net:z # tun device
#      - ${ROOT}/config/vpn:/vpn # OpenVPN configuration
#    security_opt:
#      - label:disable
#    ports:
#      - 8112:8112 # port for deluge web UI to be reachable from local network
#    command: '-f "" -r 192.168.1.0/24' # enable firewall and route local network traffic

osint:
    container_name: osint
    image:  vaultsecurity/osint:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${ROOT}/downloads:/downloads # downloads folder
      - ${ROOT}/config/osint:/config # config files

```

Also in a .env file in the same directory...
```
# Your timezone, https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
TZ=America/New_York
# UNIX PUID and PGID, find with: id $USER
PUID=typically 1000
PGID=typically 1000
# The directory where data and configuration will be stored.
ROOT=/dir to the folder where .env and compose file are

```
